### ISSUE TITLE
RuntimeError when using a plugin

### ISSUE THREAD

**Issue by Dian-S** [mitsuba-renderer/mitsuba3#1162]
## Summary

I am using a bsdf plugin with cuda_ad_rgb, and I got `RuntimeError: Unable to cast Python instance of type <class 'tuple'> to C++ type '?'`

## System configuration

System information:

  OS: Ubuntu 22.04.3
  CPU: AMD EPYC 7763
  GPU: GTX4090
  Python version: 3.9.19
  CUDA version: 12.2
  NVidia driver: 535.129.03

  Dr.Jit version: 0.4.4
  Mitsuba version: 3.5

## Description

The plugin is from https://github.com/elerac/btf-rendering and initially written for mitsuba2, and I modified it to mitsuba3. Here is the plugin after modification:
```py
import numpy as np
from .utils.btf_interpolator import BtfInterpolator
from .utils.coord_system_transfer import orthogonal2spherical, mirror_uv

import drjit as dr
from mitsuba import Bitmap, Struct, Thread, math, Properties, Frame3f, Float, Vector3f, warp, Transform3f
from mitsuba import BSDF, BSDFContext, BSDFFlags, BSDFSample3f, SurfaceInteraction3f, register_bsdf, Texture

class MeasuredBTF(BSDF):
    def __init__(self, props):
        BSDF.__init__(self, props)
        
        self.m_filename = props["filename"]
        
        if props.has_property("apply_inv_gamma"):
            self.m_apply_inv_gamma = props["apply_inv_gamma"]
        else:
            self.m_apply_inv_gamma = True

        if props.has_property("reflectance"):
            self.m_reflectance = Float(props["reflectance"])
        else:
            self.m_reflectance = Float(1.0)

        if props.has_property("power_parameter"):
            self.m_power_parameter = Float(props["power_parameter"])
        else:
            self.m_power_parameter = Float(4.0)

        if props.has_property("wrap_mode"):
            self.m_wrap_mode = str(props["wrap_mode"])
        else:
            self.m_wrap_mode = "repeat"

        self.m_transform = Transform3f(props["to_uv"].extract())
        
        self.btf = BtfInterpolator(self.m_filename, p=self.m_power_parameter)
        
        self.m_flags = BSDFFlags.DiffuseReflection | BSDFFlags.FrontSide
        self.m_components = [self.m_flags]

    def get_btf(self, wi, wo, uv):
        _, tv, pv = orthogonal2spherical(*wi)
        
        _, tl, pl = orthogonal2spherical(*wo)
        
        uv = self.m_transform.transform_affine(uv)

        if self.m_wrap_mode == "mirror":
            uv = mirror_uv(uv).T

        u, v = uv
        
        bgr = self.btf.angles_uv_to_pixel(tl, pl, tv, pv, u, v)
        
        bgr = np.clip(bgr / 255.0 * self.m_reflectance, 0, 1)
        
        if self.m_apply_inv_gamma:
            bgr **= 2.2

        return Vector3f(bgr[..., ::-1])

    def sample(self, ctx, si, sample1, sample2, active):
        """
        BSDF sampling
        """
        cos_theta_i = Frame3f.cos_theta(si.wi)

        active &= cos_theta_i > 0

        bs = BSDFSample3f()
        bs.wo  = warp.square_to_cosine_hemisphere(sample2)
        bs.pdf = warp.square_to_cosine_hemisphere_pdf(bs.wo)
        bs.eta = 1.0
        bs.sampled_type = +BSDFFlags.DiffuseReflection
        bs.sampled_component = 0

        value = self.get_btf(si.wi, bs.wo, si.uv) / Frame3f.cos_theta(bs.wo)

        return ( bs, dr.select(active & (bs.pdf > 0.0), value, Vector3f(0)) )

    def eval(self, ctx, si, wo, active):
        """
        Emitter sampling
        """
        if not ctx.is_enabled(BSDFFlags.DiffuseReflection):
            return Vector3f(0)

        cos_theta_i = Frame3f.cos_theta(si.wi) 
        cos_theta_o = Frame3f.cos_theta(wo)

        value = self.get_btf(si.wi, wo, si.uv) * math.InvPi

        return dr.select((cos_theta_i > 0.0) & (cos_theta_o > 0.0), value, Vector3f(0))

    def pdf(self, ctx, si, wo, active):
        if not ctx.is_enabled(BSDFFlags.DiffuseReflection):
            return Vector3f(0)

        cos_theta_i = Frame3f.cos_theta(si.wi)
        cos_theta_o = Frame3f.cos_theta(wo)

        pdf = warp.square_to_cosine_hemisphere_pdf(wo)

        return dr.select((cos_theta_i > 0.0) & (cos_theta_o > 0.0), pdf, 0.0)
    
    def eval_pdf(self, ctx, si, wo, active):
        return active, self.pdf(ctx, si, wo, active)

    def traverse(self, callback):
        callback.put_parameter()

    def parameters_changed(self, keys):
        print("there is nothing to do here")

    def to_string(self):
        return ('MyBSDF[\n'
                '    eta=1,\n'
                '    tint=1,\n'
                ']')
```
And this is bug report:
```py
Traceback (most recent call last):
  File "/home/dian/test/rendering.py", line 39, in <module>
    main()
  File "/home/dian/test/rendering.py", line 34, in main
    film = render(scene)
  File "/home/dian/.conda/envs/mitsuba3/lib/python3.9/site-packages/mitsuba/python/util.py", line 522, in render
    return dr.custom(_RenderOp, scene, sensor, params, integrator,
  File "/home/dian/.conda/envs/mitsuba3/lib/python3.9/site-packages/drjit/router.py", line 5776, in custom
    output = inst.eval(**{ k: _dr.detach(v) for k, v in kwargs.items() })
  File "/home/dian/.conda/envs/mitsuba3/lib/python3.9/site-packages/mitsuba/python/util.py", line 377, in eval
    return self.integrator.render(
RuntimeError: Unable to cast Python instance of type <class 'tuple'> to C++ type '?' (#define PYBIND11_DETAILED_ERROR_MESSAGES or compile in debug mode for details)
```

## Steps to reproduce

I import the plugin in `main()`, and register with `register_bsdf('measuredbtf', lambda props: MeasuredBTF(props))`. Then it crashed when rendering.

Any help would be greatly appreciated.

**Comment by merlinND** [comment]
Hi @Dian-S,

My first guess would be that the return types or signatures of the functions defined in the custom BSDF do not match the interface. For example, I noticed:
`eval_pdf() -> return active, self.pdf(...)` whereas it is supposed to return `Float, Spectrum`.

If that's not it, then you could:
- Follow the error message to get more information: "`#define PYBIND11_DETAILED_ERROR_MESSAGES` or compile in debug mode for details"
- Start back from the custom BSDF of [this tutorial](https://mitsuba.readthedocs.io/en/latest/src/others/custom_plugin.html), and slowly introduce the  custom methods one by one until it crashes. This will tell you which part of the custom plugin is not working.

**Comment by Dian-S** [comment]
Hi @merlinND ,
Your guess is right, I modified `eval_pdf()` to `return self.eval(ctx, si, wo, active), self.pdf(ctx, si, wo, active)`, and it works fine.
Thanks a lot as this problem bothers me for a long time.
