### ISSUE TITLE
AttributeError: module 'mitsuba' has no attribute 'set_variant'

### ISSUE THREAD

**Issue by arpan-kusari** [mitsuba-renderer/mitsuba3#1165]
I am trying to run the hello world example of mitsuba and getting the error in the title. I am using Ubuntu 22.04 with Python version 3.10.12 and installed mitsuba (and dr.jit) without error using 'pip mitsuba'. I confirm that mitsuba version 3.5.0 and drjit version 0.4.4 has been installed. But when I import and run mi.set_variant('scalar_rgb'), it gives me the AttributeError. From nvidia-smi, this is the output - 

+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Quadro RTX 6000                On  | 00000000:3B:00.0 Off |                  Off |
| 33%   29C    P8               4W / 260W |      6MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      2143      G   /usr/lib/xorg/Xorg                            4MiB |
+---------------------------------------------------------------------------------------+

**Comment by merlinND** [comment]
Hello @arpan-kusari,

Are you sure that the Python interpreter that you tried to import `mitsuba` with is the same that was used to pip-install the package?

Please try creating a virtual environment and importing it there:

```bash
mkdir test_dir
cd test_dir

python3 -m venv .venv
source ./.venv/bin/activate
pip install mitsuba
python

>>> import mitsuba as mi
>>> mi.set_variant("cuda_ad_rgb")
>>> scene = mi.load_dict(mi.cornell_box())
```

**Comment by ivantishchenko** [comment]
I also get the same issue. Downgrading to Python 3.8 did not help. I'm using Driver Version: 575.64.

```
─ python mitsuba.py
Traceback (most recent call last):
  File "mitsuba.py", line 1, in <module>
    import mitsuba
  File "/net/w49/data/intern/tishchenko/src/light-estimation/mitsuba.py", line 2, in <module>
    mitsuba.set_variant('scalar_rgb')
AttributeError: partially initialized module 'mitsuba' has no attribute 'set_variant' (most likely due to a circular import)
```

**Comment by merlinND** [comment]
Hello @ivantishchenko,

Mitsuba should work out-of-the-box after `pip install mitsuba` on Python 3.10+. Can you please try the following steps to make sure it is installed correctly:

```bash
$ mkdir test_pip && cd test_pip
$ python3.12 -m venv .venv
$ source ./.venv/bin/activate
$ pip install mitsuba
Collecting mitsuba
  Using cached mitsuba-3.7.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (6.9 kB)
Collecting drjit==1.1.0 (from mitsuba)
  Using cached drjit-1.1.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.1 kB)
Using cached mitsuba-3.7.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (61.7 MB)
Using cached drjit-1.1.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.8 MB)
Installing collected packages: drjit, mitsuba
Successfully installed drjit-1.1.0 mitsuba-3.7.0
$ python -c "import mitsuba as mi; mi.set_variant('llvm_ad_rgb'); print(mi.Float([1, 2, 3]))"
[1, 2, 3]

**Comment by ivantishchenko** [comment]
@merlinND 
I repeated the steps but with `python3.11` on my machine:

```
╰─ python -c "import mitsuba as mi; mi.set_variant('llvm_ad_rgb'); print(mi.Float([1, 2, 3]))" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/net/w49/data/intern/tishchenko/src/light-estimation/test_pip/mitsuba.py", line 4, in <module>
    mi.set_variant('scalar_rgb')
    ^^^^^^^^^^^^^^
AttributeError: partially initialized module 'mitsuba' has no attribute 'set_variant' (most likely due to a circular import)
```

**Comment by merlinND** [comment]
Hello @ivantishchenko,

Have you run the steps on a fully fresh shell and virtual environment? Have you checked that `mitsuba` is not already on your Python search path for some other reason? (e.g. `PYTHONPATH` environment variable, previous `source setpath.sh`, `pip install mitsuba` run with system-level `pip`, etc).

**Comment by ivantishchenko** [comment]
Found out the issue. 🤦🏻 I had a file `mitsuba.py` in the root of my codebase with the "hello-world" snipped from `README.md`. This somehow caused a circular import. Now that I renamed this file everything and can run everything.

@merlinND Thank you for your support! ❤️ I'm unblocked and can proceed further with `mitsuba`
