### ISSUE TITLE
Custom wheel building failed

### ISSUE THREAD

**Issue by Oitron** [mitsuba-renderer/mitsuba3#1170]
## Description

Hi, I've written several new plugins in C++ (sensors, integrators ...) based on Mitsuba 3, just to implement a simple serialization functionality of output rays. I have built the project and when I ran the executable for testing there were no problems. And I also want to use my own plugin in python interface, but as soon as I try to build as a wheel in Python environment, it failed. 
I don't know if some modification need to be done in `setup.py` file or...
And I really didn't find something helpful in Doc...

I simply run this command `pip install .` in console under root directory of Mitsuba, which is the same location where we put `setup.py` file. And I got these errors :

```
FAILED: Release/python/mitsuba/__init__.pyi D:/XU/These/Code/Mitsuba/mitsuba3-vk/_skbuild/win-amd64-3.12/cmake-build/Release/python/mitsuba/__init__.pyi
      C:\Windows\system32\cmd.exe /C "cd /D D:\XU\These\Code\Mitsuba\mitsuba3-vk\_skbuild\win-amd64-3.12\cmake-build\src\python && C:\Users\kxu02\AppData\Local\Temp\pip-build-env-rihps_9s\overlay\Lib\site-packages\cmake\data\bin\cmake.exe -E env PYTHONPATH=D:\XU\These\Code\Mitsuba\mitsuba3-vk\_skbuild\win-amd64-3.12\cmake-build\Release\python;C:\Users\kxu02\AppData\Local\Temp\pip-build-env-rihps_9s\site C:/Users/kxu02/AppData/Local/Programs/Python/Python312/python.exe -Xutf8 D:/XU/These/Code/Mitsuba/mitsuba3-vk/src/python/../../resources/generate_stub_files.py D:/XU/These/Code/Mitsuba/mitsuba3-vk/_skbuild/win-amd64-3.12/cmake-build/Release/python/mitsuba"
      Traceback (most recent call last):
        File "D:\XU\These\Code\Mitsuba\mitsuba3-vk\_skbuild\win-amd64-3.12\cmake-build\Release\python\mitsuba\__init__.py", line 107, in __getattribute__
          _import('mitsuba.mitsuba_' + variant + '_ext'),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\kxu02\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 921, in _load_unlocked
        File "<frozen importlib._bootstrap>", line 813, in module_from_spec
        File "<frozen importlib._bootstrap_external>", line 1289, in create_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
      ImportError: pybind11::detail::get_type_info: unable to find type info for "drjit::Array<float,0>"

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "D:\XU\These\Code\Mitsuba\mitsuba3-vk\resources\generate_stub_files.py", line 369, in <module>
          buffer, submodules = process_module(mi, top_module=True)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\XU\These\Code\Mitsuba\mitsuba3-vk\resources\generate_stub_files.py", line 305, in process_module
          for k in dir(m):
                   ^^^^^^
        File "D:\XU\These\Code\Mitsuba\mitsuba3-vk\_skbuild\win-amd64-3.12\cmake-build\Release\python\mitsuba\__init__.py", line 253, in __getattribute__

          result = module.__getattribute__(key)

                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

        File "D:\XU\These\Code\Mitsuba\mitsuba3-vk\_skbuild\win-amd64-3.12\cmake-build\Release\python\mitsuba\__init__.py", line 115, in __getattribute__

          raise AttributeError(e)

      AttributeError: pybind11::detail::get_type_info: unable to find type info for "drjit::Array<float,0>"

      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "C:\Users\kxu02\AppData\Local\Temp\pip-build-env-rihps_9s\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 674, in setup
          cmkr.make(make_args, install_target=cmake_install_target, env=env)
        File "C:\Users\kxu02\AppData\Local\Temp\pip-build-env-rihps_9s\overlay\Lib\site-packages\skbuild\cmaker.py", line 697, in make
          self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
        File "C:\Users\kxu02\AppData\Local\Temp\pip-build-env-rihps_9s\overlay\Lib\site-packages\skbuild\cmaker.py", line 742, in make_impl
          raise SKBuildError(msg)

      An error occurred while building with CMake.
        Command:
          'C:\Users\kxu02\AppData\Local\Temp\pip-build-env-rihps_9s\overlay\Lib\site-packages\cmake\data\bin/cmake.exe' --build . --target install --config Release --
        Install target:
          install
        Source directory:
          D:\XU\These\Code\Mitsuba\mitsuba3-vk
        Working directory:
          D:\XU\These\Code\Mitsuba\mitsuba3-vk\_skbuild\win-amd64-3.12\cmake-build
      Please check the install target is valid and see CMake's output for more information.
```

## System configuration

On Windows 10, Visual Studio Community 2022 (64-bit) - Version 17.5.2
  Dr.Jit version: 0.4.4
  Mitsuba version: 3.5.0

******
I'll continue to search into the output log, If someone had this kind of issue before, please help me, Tks!!!

**Comment by merlinND** [comment]
Hello @Oitron,

This sounds similar to #1147, could you please check the solution there and let us know if it fixed it for you?
