### ISSUE TITLE
The CUDA backend hasn't been initialized

### ISSUE THREAD

**Issue by A0405u** [mitsuba-renderer/mitsuba3#1221]
## System configuration

System information:

  OS: Ubuntu 22.04.3 LTS
  CPU: AMD Ryzen 7 5700G with Radeon Graphics
  GPU: NVIDIA GeForce RTX 2080
  Python: 3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0]
  NVidia driver: 552.44
  CUDA: 12.5.82
  LLVM: 15.0.7

  Dr.Jit: 0.4.6
  Mitsuba: 3.5.2
     Is custom build? False
     Compiled with: GNU 10.2.1
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb

## Description

I was trying to use CUDA in the Shape optimization tutorial and was unable to turn in on, it gives the error on the line with `mi.set_variant(cuda_ad_rgb)`. 

I am using Ubuntu through WSL 2 on Windows 11. I've installed CUDA Toolkit for WSL 2 as stated in [this article](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/). 

Here is the output of the ``nvcc --version`` command:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Jun__6_02:18:23_PDT_2024
Cuda compilation tools, release 12.5, V12.5.82
Build cuda_12.5.r12.5/compiler.34385749_0
```

Here is the output of the `nvidia-smi` command:
```
+-----------------------------------------------------------------------------------------+ 
| NVIDIA-SMI 550.76.01              Driver Version: 552.44         CUDA Version: 12.4     | 
|-----------------------------------------+------------------------+----------------------+ 
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC | 
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. | 
|                                         |                        |               MIG M. | 
|=========================================+========================+======================| 
|   0  NVIDIA GeForce RTX 2080        On  |   00000000:01:00.0  On |                  N/A | 
| 33%   35C    P8             21W /  245W |    2106MiB /   8192MiB |      4%      Default | 
|                                         |                        |                  N/A | 
+-----------------------------------------+------------------------+----------------------+ 

+-----------------------------------------------------------------------------------------+ 
| Processes:                                                                              | 
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory | 
|        ID   ID                                                               Usage      | 
|=========================================================================================| 
|    0   N/A  N/A        25      G   /Xwayland                                   N/A      | 
|    0   N/A  N/A       150      G   /Xwayland                                   N/A      | 
+-----------------------------------------------------------------------------------------+
```

When using `torch.cuda.is_available()` I'm having `True`.

Output of the error occured:
```
Traceback (most recent call last):
  File "/home/a0405u/.local/lib/python3.10/site-packages/mitsuba/__init__.py", line 107, in __getattribute__
    _import('mitsuba.mitsuba_' + variant + '_ext'),
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: jit_init_thread_state(): the CUDA backend hasn't been initialized. Make sure to call jit_init(JitBackend::CUDA) to properly initialize this backend.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/a0405u/difren/shape_optimization/main.py", line 6, in <module>
    mi.set_variant('cuda_ad_rgb', 'llvm_ad_rgb')
  File "/home/a0405u/.local/lib/python3.10/site-packages/mitsuba/__init__.py", line 317, in set_variant
    _import('mitsuba.ad.integrators')
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/a0405u/.local/lib/python3.10/site-packages/mitsuba/python/ad/__init__.py", line 2, in <module>
    from .integrators import *
  File "/home/a0405u/.local/lib/python3.10/site-packages/mitsuba/python/ad/integrators/__init__.py", line 25, in <module>
    importlib.import_module('mitsuba.ad.integrators.' + name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/a0405u/.local/lib/python3.10/site-packages/mitsuba/python/ad/integrators/prb_basic.py", line 6, in <module>
    from .common import RBIntegrator
  File "/home/a0405u/.local/lib/python3.10/site-packages/mitsuba/python/ad/integrators/common.py", line 8, in <module>
    class ADIntegrator(mi.CppADIntegrator):
  File "/home/a0405u/.local/lib/python3.10/site-packages/mitsuba/__init__.py", line 253, in __getattribute__
    result = module.__getattribute__(key)
  File "/home/a0405u/.local/lib/python3.10/site-packages/mitsuba/__init__.py", line 115, in __getattribute__
    raise AttributeError(e)
AttributeError: jit_init_thread_state(): the CUDA backend hasn't been initialized. Make sure to call jit_init(JitBackend::CUDA) to properly initialize this backend.
```

## Steps to reproduce

1. Install Ubuntu through WSL
2. Install CUDA Toolkit and Mitsuba
3. Import Mitsuba and set variant to `cuda_ad_rgb`

**Comment by njroussel** [comment]
Hi @A0405u 

This is an upstream issue with Nvidia's OptiX on which Mitsuba relies. To my latest knowledge, OptiX is not yet supported in WSL.  In short, OptiX is usually shipped with your driver, but for _reasons_ that is not happening with WSL.

You'll find more details on the Nvidia forums about this. This thread seems to be the most active, if you want to stay up to date: https://forums.developer.nvidia.com/t/problem-running-optix-7-6-in-wsl/239355
