### ISSUE TITLE
Build is failing . Drjit error

### ISSUE THREAD

**Issue by sujoyrc** [mitsuba-renderer/mitsuba3#1237]
I am compiling this on a Ubuntu machine

```
OS: Ubuntu 20.04.6 LTS x86_64
Host: OpenStack Nova 26.2.1 
Kernel: 5.4.0-187-generic 
Shell: bash 5.0.17 
CPU: AMD EPYC 7702 (30) @ 1.996GHz 
GPU: NVIDIA 00:08.0 NVIDIA Corporation Device 20b2
Memory: 27770MiB / 216257MiB 
```

the commands I ran

```
source radioMaps_venv_3.10/bin/activate
export PATH=/data3/RadioMaps/cmake-3.30.0-linux-x86_64/bin/:$PATH
cmake -G Ninja .. -DCMAKE_C_COMPILER=`which gcc-9` -DCMAKE_CXX_COMPILER=`which g++-9`   -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON -DPYTHON_INCLUDE_DIR=$(python -c "import sysconfig; print(sysconfig.get_path('include'))") -DPYTHON_LIBRARY=$(python -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR'))")
ninja
```

```
(radioMaps_venv_3.10) ubuntu@gpu:/data3/RadioMaps/mitsuba3/build$ cmake --version
cmake version 3.30.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

The cmake worked but ninja build is failing.

```
(radioMaps_venv_3.10) ubuntu@gpu:/data3/RadioMaps/mitsuba3/build$ ninja
[4/718] Generating ../../../../python/drjit/interop.pyi
FAILED: python/drjit/interop.pyi /data3/RadioMaps/mitsuba3/build/python/drjit/interop.pyi 
cd /data3/RadioMaps/mitsuba3/build/ext/drjit/src/python && /usr/bin/python3.8 /data3/RadioMaps/mitsuba3/ext/nanobind/src/stubgen.py -q -i /data3/RadioMaps/mitsuba3/build/ext/../python/drjit/.. -p /data3/RadioMaps/mitsuba3/ext/drjit/src/python/../../drjit/stubs.pat -m drjit.interop -o /data3/RadioMaps/mitsuba3/build/ext/../python/drjit/interop.pyi
Traceback (most recent call last):
  File "/data3/RadioMaps/mitsuba3/build/ext/../python/drjit/../drjit/__init__.py", line 5, in <module>
    from . import _drjit_ext as _drjit_ext
ImportError: libdrjit-extra.so: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data3/RadioMaps/mitsuba3/ext/nanobind/src/stubgen.py", line 1391, in <module>
    main()
  File "/data3/RadioMaps/mitsuba3/ext/nanobind/src/stubgen.py", line 1324, in main
    mod_imported = importlib.import_module(mod)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data3/RadioMaps/mitsuba3/build/ext/../python/drjit/../drjit/__init__.py", line 17, in <module>
    raise err
ImportError: Could not import the Dr.Jit binary extension. It is likely that the Python version for which Dr.Jit was compiled (3.8.10) is incompatible with the current interpreter (3.8.10).
[6/718] Generating ../../../../python/drjit/py.typed, ../../../../python/drjit/__init__.pyi
FAILED: python/drjit/py.typed python/drjit/__init__.pyi /data3/RadioMaps/mitsuba3/build/python/drjit/py.typed /data3/RadioMaps/mitsuba3/build/python/drjit/__init__.pyi 
cd /data3/RadioMaps/mitsuba3/build/ext/drjit/src/python && /usr/bin/python3.8 /data3/RadioMaps/mitsuba3/ext/nanobind/src/stubgen.py -q -i /data3/RadioMaps/mitsuba3/build/ext/../python/drjit/.. -p /data3/RadioMaps/mitsuba3/ext/drjit/src/python/../../drjit/stubs.pat -M /data3/RadioMaps/mitsuba3/build/ext/../python/drjit/py.typed -m drjit -o /data3/RadioMaps/mitsuba3/build/ext/../python/drjit/__init__.pyi
Traceback (most recent call last):
  File "/data3/RadioMaps/mitsuba3/build/ext/../python/drjit/../drjit/__init__.py", line 5, in <module>
    from . import _drjit_ext as _drjit_ext
ImportError: libdrjit-extra.so: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data3/RadioMaps/mitsuba3/ext/nanobind/src/stubgen.py", line 1391, in <module>
    main()
  File "/data3/RadioMaps/mitsuba3/ext/nanobind/src/stubgen.py", line 1324, in main
    mod_imported = importlib.import_module(mod)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data3/RadioMaps/mitsuba3/build/ext/../python/drjit/../drjit/__init__.py", line 17, in <module>
    raise err
ImportError: Could not import the Dr.Jit binary extension. It is likely that the Python version for which Dr.Jit was compiled (3.8.10) is incompatible with the current interpreter (3.8.10).
[7/718] Generating ../../../../python/drjit/cuda/ad.pyi
FAILED: python/drjit/cuda/ad.pyi /data3/RadioMaps/mitsuba3/build/python/drjit/cuda/ad.pyi 
cd /data3/RadioMaps/mitsuba3/build/ext/drjit/src/python && /usr/bin/python3.8 /data3/RadioMaps/mitsuba3/ext/nanobind/src/stubgen.py -q -i /data3/RadioMaps/mitsuba3/build/ext/../python/drjit/.. -p /data3/RadioMaps/mitsuba3/ext/drjit/src/python/../../drjit/stubs.pat -m drjit.cuda.ad -o /data3/RadioMaps/mitsuba3/build/ext/../python/drjit/cuda/ad.pyi
Traceback (most recent call last):
  File "/data3/RadioMaps/mitsuba3/build/ext/../python/drjit/../drjit/__init__.py", line 5, in <module>
    from . import _drjit_ext as _drjit_ext
ImportError: libdrjit-extra.so: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data3/RadioMaps/mitsuba3/ext/nanobind/src/stubgen.py", line 1391, in <module>
    main()
  File "/data3/RadioMaps/mitsuba3/ext/nanobind/src/stubgen.py", line 1324, in main
    mod_imported = importlib.import_module(mod)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data3/RadioMaps/mitsuba3/build/ext/../python/drjit/../drjit/__init__.py", line 17, in <module>
    raise err
ImportError: Could not import the Dr.Jit binary extension. It is likely that the Python version for which Dr.Jit was compiled (3.8.10) is incompatible with the current interpreter (3.8.10).
[8/718] Generating ../../../../python/drjit/llvm/ad.pyi
FAILED: python/drjit/llvm/ad.pyi /data3/RadioMaps/mitsuba3/build/python/drjit/llvm/ad.pyi 
cd /data3/RadioMaps/mitsuba3/build/ext/drjit/src/python && /usr/bin/python3.8 /data3/RadioMaps/mitsuba3/ext/nanobind/src/stubgen.py -q -i /data3/RadioMaps/mitsuba3/build/ext/../python/drjit/.. -p /data3/RadioMaps/mitsuba3/ext/drjit/src/python/../../drjit/stubs.pat -m drjit.llvm.ad -o /data3/RadioMaps/mitsuba3/build/ext/../python/drjit/llvm/ad.pyi
Traceback (most recent call last):
  File "/data3/RadioMaps/mitsuba3/build/ext/../python/drjit/../drjit/__init__.py", line 5, in <module>
    from . import _drjit_ext as _drjit_ext
ImportError: libdrjit-extra.so: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data3/RadioMaps/mitsuba3/ext/nanobind/src/stubgen.py", line 1391, in <module>
    main()
  File "/data3/RadioMaps/mitsuba3/ext/nanobind/src/stubgen.py", line 1324, in main
    mod_imported = importlib.import_module(mod)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data3/RadioMaps/mitsuba3/build/ext/../python/drjit/../drjit/__init__.py", line 17, in <module>
    raise err
ImportError: Could not import the Dr.Jit binary extension. It is likely that the Python version for which Dr.Jit was compiled (3.8.10) is incompatible with the current interpreter (3.8.10).
[9/718] Generating ../../../../python/drjit/cuda/py.typed, ../../../../python/drjit/cuda/__init__.pyi
FAILED: python/drjit/cuda/py.typed python/drjit/cuda/__init__.pyi /data3/RadioMaps/mitsuba3/build/python/drjit/cuda/py.typed /data3/RadioMaps/mitsuba3/build/python/drjit/cuda/__init__.pyi 
cd /data3/RadioMaps/mitsuba3/build/ext/drjit/src/python && /usr/bin/python3.8 /data3/RadioMaps/mitsuba3/ext/nanobind/src/stubgen.py -q -i /data3/RadioMaps/mitsuba3/build/ext/../python/drjit/.. -p /data3/RadioMaps/mitsuba3/ext/drjit/src/python/../../drjit/stubs.pat -M /data3/RadioMaps/mitsuba3/build/ext/../python/drjit/cuda/py.typed -m drjit.cuda -o /data3/RadioMaps/mitsuba3/build/ext/../python/drjit/cuda/__init__.pyi
Traceback (most recent call last):
  File "/data3/RadioMaps/mitsuba3/build/ext/../python/drjit/../drjit/__init__.py", line 5, in <module>
    from . import _drjit_ext as _drjit_ext
ImportError: libdrjit-extra.so: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data3/RadioMaps/mitsuba3/ext/nanobind/src/stubgen.py", line 1391, in <module>
    main()
  File "/data3/RadioMaps/mitsuba3/ext/nanobind/src/stubgen.py", line 1324, in main
    mod_imported = importlib.import_module(mod)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data3/RadioMaps/mitsuba3/build/ext/../python/drjit/../drjit/__init__.py", line 17, in <module>
    raise err
ImportError: Could not import the Dr.Jit binary extension. It is likely that the Python version for which Dr.Jit was compiled (3.8.10) is incompatible with the current interpreter (3.8.10).
[11/718] Generating ../../../../python/drjit/llvm/py.typed, ../../../../python/drjit/llvm/__init__.pyi
FAILED: python/drjit/llvm/py.typed python/drjit/llvm/__init__.pyi /data3/RadioMaps/mitsuba3/build/python/drjit/llvm/py.typed /data3/RadioMaps/mitsuba3/build/python/drjit/llvm/__init__.pyi 
cd /data3/RadioMaps/mitsuba3/build/ext/drjit/src/python && /usr/bin/python3.8 /data3/RadioMaps/mitsuba3/ext/nanobind/src/stubgen.py -q -i /data3/RadioMaps/mitsuba3/build/ext/../python/drjit/.. -p /data3/RadioMaps/mitsuba3/ext/drjit/src/python/../../drjit/stubs.pat -M /data3/RadioMaps/mitsuba3/build/ext/../python/drjit/llvm/py.typed -m drjit.llvm -o /data3/RadioMaps/mitsuba3/build/ext/../python/drjit/llvm/__init__.pyi
Traceback (most recent call last):
  File "/data3/RadioMaps/mitsuba3/build/ext/../python/drjit/../drjit/__init__.py", line 5, in <module>
    from . import _drjit_ext as _drjit_ext
ImportError: libdrjit-extra.so: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data3/RadioMaps/mitsuba3/ext/nanobind/src/stubgen.py", line 1391, in <module>
    main()
  File "/data3/RadioMaps/mitsuba3/ext/nanobind/src/stubgen.py", line 1324, in main
    mod_imported = importlib.import_module(mod)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data3/RadioMaps/mitsuba3/build/ext/../python/drjit/../drjit/__init__.py", line 17, in <module>
    raise err
ImportError: Could not import the Dr.Jit binary extension. It is likely that the Python version for which Dr.Jit was compiled (3.8.10) is incompatible with the current interpreter (3.8.10).
[12/718] Generating ../../../../python/drjit/detail.pyi
FAILED: python/drjit/detail.pyi /data3/RadioMaps/mitsuba3/build/python/drjit/detail.pyi 
cd /data3/RadioMaps/mitsuba3/build/ext/drjit/src/python && /usr/bin/python3.8 /data3/RadioMaps/mitsuba3/ext/nanobind/src/stubgen.py -q -i /data3/RadioMaps/mitsuba3/build/ext/../python/drjit/.. -p /data3/RadioMaps/mitsuba3/ext/drjit/src/python/../../drjit/stubs.pat -m drjit.detail -o /data3/RadioMaps/mitsuba3/build/ext/../python/drjit/detail.pyi
Traceback (most recent call last):
  File "/data3/RadioMaps/mitsuba3/build/ext/../python/drjit/../drjit/__init__.py", line 5, in <module>
    from . import _drjit_ext as _drjit_ext
ImportError: libdrjit-extra.so: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data3/RadioMaps/mitsuba3/ext/nanobind/src/stubgen.py", line 1391, in <module>
    main()
  File "/data3/RadioMaps/mitsuba3/ext/nanobind/src/stubgen.py", line 1324, in main
    mod_imported = importlib.import_module(mod)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data3/RadioMaps/mitsuba3/build/ext/../python/drjit/../drjit/__init__.py", line 17, in <module>
    raise err
ImportError: Could not import the Dr.Jit binary extension. It is likely that the Python version for which Dr.Jit was compiled (3.8.10) is incompatible with the current interpreter (3.8.10).
[14/718] Generating ../../../../python/drjit/scalar/__init__.pyi
FAILED: python/drjit/scalar/__init__.pyi /data3/RadioMaps/mitsuba3/build/python/drjit/scalar/__init__.pyi 
cd /data3/RadioMaps/mitsuba3/build/ext/drjit/src/python && /usr/bin/python3.8 /data3/RadioMaps/mitsuba3/ext/nanobind/src/stubgen.py -q -i /data3/RadioMaps/mitsuba3/build/ext/../python/drjit/.. -p /data3/RadioMaps/mitsuba3/ext/drjit/src/python/../../drjit/stubs.pat -m drjit.scalar -o /data3/RadioMaps/mitsuba3/build/ext/../python/drjit/scalar/__init__.pyi
Traceback (most recent call last):
  File "/data3/RadioMaps/mitsuba3/build/ext/../python/drjit/../drjit/__init__.py", line 5, in <module>
    from . import _drjit_ext as _drjit_ext
ImportError: libdrjit-extra.so: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data3/RadioMaps/mitsuba3/ext/nanobind/src/stubgen.py", line 1391, in <module>
    main()
  File "/data3/RadioMaps/mitsuba3/ext/nanobind/src/stubgen.py", line 1324, in main
    mod_imported = importlib.import_module(mod)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data3/RadioMaps/mitsuba3/build/ext/../python/drjit/../drjit/__init__.py", line 17, in <module>
    raise err
ImportError: Could not import the Dr.Jit binary extension. It is likely that the Python version for which Dr.Jit was compiled (3.8.10) is incompatible with the current interpreter (3.8.10).
[16/718] Generating ../../../../python/drjit/ast.pyi
FAILED: python/drjit/ast.pyi /data3/RadioMaps/mitsuba3/build/python/drjit/ast.pyi 
cd /data3/RadioMaps/mitsuba3/build/ext/drjit/src/python && /usr/bin/python3.8 /data3/RadioMaps/mitsuba3/ext/nanobind/src/stubgen.py -q -i /data3/RadioMaps/mitsuba3/build/ext/../python/drjit/.. -p /data3/RadioMaps/mitsuba3/ext/drjit/src/python/../../drjit/stubs.pat -m drjit.ast -o /data3/RadioMaps/mitsuba3/build/ext/../python/drjit/ast.pyi
Traceback (most recent call last):
  File "/data3/RadioMaps/mitsuba3/build/ext/../python/drjit/../drjit/__init__.py", line 5, in <module>
    from . import _drjit_ext as _drjit_ext
ImportError: libdrjit-extra.so: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data3/RadioMaps/mitsuba3/ext/nanobind/src/stubgen.py", line 1391, in <module>
    main()
  File "/data3/RadioMaps/mitsuba3/ext/nanobind/src/stubgen.py", line 1324, in main
    mod_imported = importlib.import_module(mod)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data3/RadioMaps/mitsuba3/build/ext/../python/drjit/../drjit/__init__.py", line 17, in <module>
    raise err
ImportError: Could not import the Dr.Jit binary extension. It is likely that the Python version for which Dr.Jit was compiled (3.8.10) is incompatible with the current interpreter (3.8.10).
[35/718] Building CXX object ext/embree/kernels/CMakeFiles/embree_avx512.dir/bvh/bvh_intersector_hybrid16_bvh4.cpp.avx512.cpp.o
ninja: build stopped: subcommand failed.
```
I need the build because I want to run https://github.com/NVlabs/instant-rm?tab=readme-ov-file - However I have not yet included the cuda_ad_mono_polarized recommended there since build was failing.

**Comment by merlinND** [comment]
Thanks for all the details logs. I was able to reproduce your error.

During the build process, Mitsuba generates Python stub files, which involves importing the recently-build DrJit Python module. The DrJit Python module looks for `libdrjit-autodiff.so`, which *is* built and ready to use.
But for some reason, when enabling `-DCMAKE_BUILD_WITH_INSTALL_RPATH=ON`, that library is no longer found.
The real question is why do you need to enable it in the first place, since on an Ubuntu system with GCC or Clang, this shouldn't be needed.

But anyway, here is a workaround that fixed the import error for me:

```
cd build
export LD_LIBRARY_PATH="$(pwd):$LD_LIBRARY_PATH"
ninja
```

**Comment by sujoyrc** [comment]
Finally finally finally @merlinND I could do the full build and run the three sample notebooks in instant-rm . BIG BIG thank you  !!!
