### ISSUE TITLE
[❔ other question] question during creating custom emitter plugin

### ISSUE THREAD

**Issue by RupertPaoZ** [mitsuba-renderer/mitsuba3#131]
## Summary

I am not sure what error I have made during creating an emitter plugin.

## System configuration

- Platform: Windows 10
- Compiler: VS2019
- Python version: 3.8.10
- Mitsuba 3 version: 3.0.0
- Compiled variants:
    * `scalar_rgb`
    * `scalar_rgb` 
    * `scalar_spectral` 
    * `scalar_mono_polarized` 
    * `scalar_spectral_polarized` 
    * `llvm_spectral_polarized`
    * `cuda_spectral_polarized`
    * `llvm_ad_rgb`
    * `cuda_ad_rgb`

## Description

I want to create a custom emitter plugin. As a consequence, I try to recreate a python plugin of point light to know the skeleton well. I do this according to the `point.cpp`. However, there are some errors that confuse me. I would appreciate it if you can help me.

## Steps to reproduce

1.following is my code:
 
```
from numpy import dsplit, empty
from sqlalchemy import false, null
import drjit as dr
import mitsuba as mi
from typing import List, Tuple

mi.set_variant('scalar_rgb')

class MyPLight(mi.Emitter):
    def __init__(self, props: mi.Properties) -> None:
        mi.Emitter.__init__(self, props)
        self.m_position = props.get('position', mi.Point3f([0., 0., 0.]))
        self.m_intensity = props.get('intensity', mi.Texture.D65(1.0))
        self.m_needs_sample_3 = False
        self.m_flags = mi.EmitterFlags.DeltaPosition

    def sample_ray(self, time: float, wavelength_sample: float, pos_sample: mi.Point2f, dir_sample: mi.Point2f, active: bool) -> Tuple[mi.Ray3f, mi.Color3f]:
        
        wavelengths, weight = self.sample_wavelengths(
            dr.zeros(mi.SurfaceInteraction3f), wavelength_sample, active)
        weight *= 4.0 * dr.pi
        ray = mi.Ray3f(self.m_position, 
                    mi.warp.square_to_uniform_sphere(dir_sample),
                    time, wavelengths)
        return (ray, mi.depolarizer(weight))

    def sample_direction(self, it, sample: mi.Point2f, active: bool):
        d = self.m_position - it.p
        dist2 = dr.squared_norm(d)
        inv_dist = dr.rsqrt(dist2)
        dist = dr.sqrt(dist2)

        # ds = mi.DirectionSample3f(self.m_position, 0., 0., it.time, 1., True, d*inv_dist, dist, self)
        ds = mi.DirectionSample3f()
        ds.p = self.m_position
        ds.n = 0.
        ds.uv = 0.
        ds.time = it.time
        ds.pdf = 1.
        ds.delta = True
        ds.d = d * inv_dist
        ds.dist = dist
        ds.emitter = self

        si = dr.zeros(mi.SurfaceInteraction3f)
        si.wavelengths = it.wavelengths
        spec = mi.unpolarized_spectrum(
            self.m_intensity.eval(si, active)*dr.sqr(inv_dist))

        return (ds, mi.depolarizer(spec))

    def pdf_direction(self, it, ds, Mask: bool) -> float:
        return 0.

    def eval_direction(self, it, ds, active: bool) -> mi.Color3f:
        si = dr.zeros(mi.SurfaceInteraction3f)
        si.wavelengths = it.wavelengths
        spec = mi.unpolarized_spectrum(self.m_intensity.eval(si, active) * dr.rcp(dr.squared_norm(ds.p-it.p)))
        return mi.depolarizer(spec)

    def sample_position(self, time: float, sample: mi.Point2f, active: bool) -> Tuple[mi.PositionSample3f, float]:
        ps = dr.zeros(mi.PositionSample3f)
        ps.p = self.m_position
        ps.time = time
        ps.delta = True
        return (ps, float(1.))
    
    def sample_wavelengths(self, si, sample: float, active: bool) -> Tuple[mi.Color0f, mi.Color3f]:
        return self.m_intensity.sample_spectrum(
            si, mi.sample_shifted(sample), active
        )

    def eval(self, si, active: bool) -> mi.Color3f:
        return 0.

    def bbox(self) -> mi.BoundingBox3f:
        return mi.BoundingBox3f(self.m_position)

    def traverse(self, callback: mi.TraversalCallback):
        callback.put_parameter('position', self.m_position, mi.ParamFlags.NonDifferentiable)
        callback.put_object('intensity', self.m_intensity, mi.ParamFlags.Differentiable)

    def parameters_changed(self, keys: List[str] = ...) -> None:
        print("🏝️ nothing to do here 🏝️")

    def to_string(self):
        return ('MyPL[\n'
                '    position=%s,\n'
                '    intensity=%s,\n'
                ']' % (self.m_position, self.m_intensity))


mi.register_emitter("mypl", lambda props: MyPLight(props))

my_pl = mi.load_dict({
    'type' : 'mypl',
    'position' : [0.0, -1.0, 5.0],
    'intensity' : {
        'type': 'spectrum',
        'value': 10.0,
    }
})

scene = mi.load_dict({
    'type': 'scene',
    'integrator': {
        'type': 'path',
    },
    'light': my_pl,
    'sphere' : {
        'type': 'sphere',
        'bsdf': {
            'type': 'diffuse',
            'reflectance': {
                'type': 'rgb',
                'value': [0.2, 0.25, 0.7]
            }
        },
    },
    'sensor': {
        'type': 'perspective',
        'to_world': mi.ScalarTransform4f.look_at(origin=[0, -5, 5],
                                                 target=[0, 0, 0],
                                                 up=[0, 0, 1]),
    }
})

image = mi.render(scene)

mi.Bitmap(image).convert(srgb_gamma=True).write('mypl.exr')
```

2. the bug report is:
```
Traceback (most recent call last):
  File ".\mypl.py", line 145, in <module>
    image = mi.render(scene)
  File "D:\Code\mitsuba3\build\Release\python\mitsuba\python\util.py", line 496, in render       
    return dr.custom(_RenderOp, scene, sensor, params, integrator,
  File "D:\Code\mitsuba3\build\Release\python\drjit\router.py", line 5566, in custom
    output = inst.eval(**{ k: _dr.detach(v) for k, v in kwargs.items() })
  File "D:\Code\mitsuba3\build\Release\python\mitsuba\python\util.py", line 358, in eval
    return self.integrator.render(
  File ".\mypl.py", line 34, in sample_direction
    ds = mi.DirectionSample3f()
  File "D:\Code\mitsuba3\build\Release\python\mitsuba\__init__.py", line 267, in __getattribute__
    _tls.cache[(variant, submodule, key)] = result
UnboundLocalError: local variable 'result' referenced before assignment
```

**Comment by ziyi-zhang** [comment]
Hi @RupertPaoZ,
`ds.emitter` stores an EmitterPtr. Passing `self` to it might not work. Could you try to cast it to a pointer type?
```Python
ds.emitter = type(ds.emitter)(self)
```

**Comment by RupertPaoZ** [comment]
Hi @ziyi-zhang 
Thanks for your help!
I replace this line as you told. However, it still doesn't work and the error messages don't change.

**Comment by RupertPaoZ** [comment]
> Hi @RupertPaoZ, `ds.emitter` stores an EmitterPtr. Passing `self` to it might not work. Could you try to cast it to a pointer type?
> 
> ```python
> ds.emitter = type(ds.emitter)(self)
> ```

I also try to use the `ptr` in `mitsuba.Object` and `id()` in python as follows:
`ds.emitter = self.ptr`,
`ds.emitter = id(self)`.
But neither of them works. And I found that the results of `self.ptr` and `id(self)` are different, so I'm not sure which one is correct.

**Comment by ziyi-zhang** [comment]
In C++, one can use the `this` pointer. 
In Python, `mi.EmitterPtr(self)` seems to be working. I am able to retrieve the emitter from `ds.emitter`. I can also call `ds.emitter.eval(si)`.

With that said, if you are using a path integrator, `ds.emitter` is never used (I checked path.cpp:183-216).
When I was running the code snippet, without the casting, it throws an "incompatible function argument" error. But with the casting (or even delete that line), it renders a blueish sphere. 

Hope this helps. You can also try `lldb_ad_rgb` mode, or run the code in debug mode with debugger.

**Comment by RupertPaoZ** [comment]
> In C++, one can use the `this` pointer. In Python, `mi.EmitterPtr(self)` seems to be working. I am able to retrieve the emitter from `ds.emitter`. I can also call `ds.emitter.eval(si)`.
> 
> With that said, if you are using a path integrator, `ds.emitter` is never used (I checked path.cpp:183-216). When I was running the code snippet, without the casting, it throws an "incompatible function argument" error. But with the casting (or even delete that line), it renders a blueish sphere.
> 
> Hope this helps. You can also try `lldb_ad_rgb` mode, or run the code in debug mode with debugger.

Thanks a lot. It works under the `llvm*` and `cuda*` mode. And I found that only under the `scalar*` mode it will cast this error.
