### ISSUE TITLE
Cannot pip install from local folder

### ISSUE THREAD

**Issue by dvicini** [mitsuba-renderer/mitsuba3#1441]
Hi,

At some point I think it was possible to install Mitsuba by running `pip install` on a local copy of the repository, i.e.,`pip install ./mitsuba3` would build and install Mitsuba from source. 

This appears to no longer work. On my Linux machine I get a number of errors of the form:

```
      .../mitsuba3/include/mitsuba/render/medium.h:134:1: error: no member named 'has_variant_override' in namespace 'drjit::detail'
      MI_CALL_TEMPLATE_END(Medium)
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      .../mitsuba3/include/mitsuba/core/class.h:262:45: note: expanded from macro 'MI_CALL_TEMPLATE_END'
          static_assert(is_detected_v<dr::detail::has_variant_override, CallSupport_>);  \
```

When removing the `static_assert` here, I get other errors about missing Dr.Jit functions or members. So the issue might be less with this specific line and more with the build setup or some missing includes (?). 

The reason I was looking into this was because I was updating the [fastsweep](https://github.com/rgl-epfl/fastsweep) package, which locally links against Dr.Jit. In the end I was able to do this by locally PIP-installing only Dr.Jit itself. Therefore, I am not blocked in any way. But this still might be worth fixing (e.g., eventually someone might want to build a Python package that has C++ code that depends on Mitsuba and not just Dr.Jit)

**Comment by merlinND** [comment]
Hi @dvicini,

This looks like a version mismatch, e.g. combining the Mitsuba commit that you have checked out together with an older DrJit. The errors you got are pointing to a change that was merged recently but are not yet part of a DrJit release.

Is it possible that when doing `pip install ./mitsuba3`, pip first installs the latest `drjit` package from PyPi (instead of your local checkout) and tries to compile Mitsuba against that?

https://github.com/mitsuba-renderer/mitsuba3/blob/54dda7b7f3ac412d43e667ce07668494de8292c3/setup.py#L61

**Comment by dvicini** [comment]
I think you are right! I think I wrongly assumed that `pip install ./mitsuba3` would also install the recursively included Dr.Jit, but that's not the case.

If I explicitly install the Dr.Jit in `ext/drjit`, I get further and it seems that the main compilation succeeds. However, I then still run into errors during stubgen:

```
      ImportError: RuntimeError: nanobind.detail.bind("ObjectPtr"): element type "N7mitsuba6ObjectE" not found.
```

I don't really have time to investigate this further at the moment, but it appears to not quite work yet

**Comment by rtabbara** [comment]
Hey again @dvicini ,

We recently had some issues related to this when preparing the recent release of Mitsuba, but I think they're squashed now with the latest commit. But please give it a go when you have the chance just to confirm that it's been fixed from your end.

**Comment by dvicini** [comment]
The stubgen still seems to fail for me, but hard to say why. This might due to our unusual linux setup. I did a clean`pip install` of the drjit in Mitsuba's ext folder (that worked) and then of Mitsuba itself (that failed):

```
      FAILED: python/mitsuba/py.typed python/mitsuba/_stubs.pyi /usr/local/google/home/vicini/code/mitsuba3/build/cp311-cp311-linux_x86_64/python/mitsuba/py.typed /usr/local/google/home/vicini/code/mitsuba3/build/cp311-cp311-linux_x86_64/python/mitsuba/_stubs.pyi
      cd /usr/local/google/home/vicini/code/mitsuba3/build/cp311-cp311-linux_x86_64/src/python && /usr/local/google/home/vicini/virtualenvs/mi/bin/python /usr/local/google/home/vicini/virtualenvs/mi/lib/python3.11/site-packages/nanobind/stubgen.py -q -i /usr/local/google/home/vicini/code/mitsuba3/build/cp311-cp311-linux_x86_64/python -p /usr/local/google/home/vicini/code/mitsuba3/src/python/stubs.pat -M /usr/local/google/home/vicini/code/mitsuba3/build/cp311-cp311-linux_x86_64/python/mitsuba/py.typed -m mitsuba.mitsuba_stubs -o /usr/local/google/home/vicini/code/mitsuba3/build/cp311-cp311-linux_x86_64/python/mitsuba/_stubs.pyi
      WARNING:root:The `mitsuba` package relies on `drjit` and needs it to be installed at a specific location. Currently, `drjit` is located at "/tmp/pip-build-env-_22v37l6/overlay/lib/python3.11/site-packages/drjit" when it is expected to be at "/usr/local/google/home/vicini/code/mitsuba3/build/cp311-cp311-linux_x86_64/python/drjit". This can happen when both packages are not installed in the same Python environment. You will very likely experience linking issues if you do not fix this.
      Traceback (most recent call last):
        File "/usr/local/google/home/vicini/code/mitsuba3/build/cp311-cp311-linux_x86_64/python/mitsuba/mitsuba_stubs/__init__.py", line 48, in <module>
          mi.set_variant(v)
      ImportError: RuntimeError: nanobind.detail.bind("ObjectPtr"): element type "N7mitsuba6ObjectE" not found.

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/usr/local/google/home/vicini/virtualenvs/mi/lib/python3.11/site-packages/nanobind/stubgen.py", line 1422, in <module>
          main()
        File "/usr/local/google/home/vicini/virtualenvs/mi/lib/python3.11/site-packages/nanobind/stubgen.py", line 1355, in main
          mod_imported = importlib.import_module(mod)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 940, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "/usr/local/google/home/vicini/code/mitsuba3/build/cp311-cp311-linux_x86_64/python/mitsuba/mitsuba_stubs/__init__.py", line 50, in <module>
          mi.set_variant('scalar_rgb')
      ImportError: std::bad_cast
```

**Comment by dvicini** [comment]
Thanks for clarifying, that makes sense. With `--no-build-isolation` it indeed works fine now!
