### ISSUE TITLE
[🐛 bug report][🔨 compilation issue] `AttributeError: pybind11::detail::get_type_info: unable to find type info for "drjit::Array<drjit::DiffArray<drjit::LLVMArray<float> >, 0ul>"`

### ISSUE THREAD

**Issue by maxfrei750** [mitsuba-renderer/mitsuba3#204]
## Summary

I compiled `drjit` myself, to benefit from https://github.com/mitsuba-renderer/drjit/pull/62. Everything concerning `drjit` seems to work well, however, if I issue

```
import mitsuba as mi
mi.set_variant('llvm_ad_rgb')
```

then I get 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mitsuba/__init__.py", line 115, in __getattribute__
    _import('mitsuba.mitsuba_' + variant + '_ext'),
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1166, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: pybind11::detail::get_type_info: unable to find type info for "drjit::Array<drjit::DiffArray<drjit::LLVMArray<float> >, 0ul>"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/mitsuba/__init__.py", line 319, in set_variant
    _import('mitsuba.ad.integrators')
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/mitsuba/python/ad/__init__.py", line 1, in <module>
    from .integrators import *
  File "/usr/local/lib/python3.8/dist-packages/mitsuba/python/ad/integrators/__init__.py", line 25, in <module>
    importlib.import_module('mitsuba.ad.integrators.' + name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.8/dist-packages/mitsuba/python/ad/integrators/emission_reparam.py", line 6, in <module>
    from .common import ADIntegrator
  File "/usr/local/lib/python3.8/dist-packages/mitsuba/python/ad/integrators/common.py", line 8, in <module>
    class ADIntegrator(mi.CppADIntegrator):
  File "/usr/local/lib/python3.8/dist-packages/mitsuba/__init__.py", line 255, in __getattribute__
    result = module.__getattribute__(key)
  File "/usr/local/lib/python3.8/dist-packages/mitsuba/__init__.py", line 122, in __getattribute__
    raise AttributeError(e)
AttributeError: pybind11::detail::get_type_info: unable to find type info for "drjit::Array<drjit::DiffArray<drjit::LLVMArray<float> >, 0ul>"
```

Using `mi.set_variant('cuda_ad_rgb')` yields a similar error, however, `mi.set_variant('scalar_rgb')` works.

## System configuration
- Platform: Ubuntu 20.04 (docker: `nvidia/cuda:11.3.0-cudnn8-runtime-ubuntu20.04`)
- Compiler: `clang10`
- Python version: `3.8`
- Mitsuba 3 version: `3.0.1`
- Compiled variants: default

## Steps to reproduce
```
pip install mitsuba
git clone -b wrap_ad --single-branch --depth 1 --recursive https://github.com/mitsuba-renderer/drjit.git
pip install ./drjit
rm -r drjit
python -c "import mitsuba as mi; mi.set_variant('llvm_ad_rgb')"
```

Using `git clone --depth 1 --recursive https://github.com/mitsuba-renderer/drjit.git` gives me the same errors.

Do I need to compile `mitsuba` as well, if I compile `drjit`?

**Comment by maxfrei750** [comment]
I was able to fix the error by compiling `drjit` and `mitsuba` in one go, instead of only compiling `drjit` and installing `mitsuba` from PyPI.

**Comment by njroussel** [comment]
Good that you figured it out! I saw this too late.
However, let me point out a couple things.

First, the `pip install mitsuba` will also install `drjit` from PyPI. I'm not 100% convinced `pip install ./drjit` will properly overwrite the PyPI installation, it seems like it's the case though.
So, just in case `pip uninstall drjit` between both operations to be sure everything is fine in the future.

Second, `mitsuba` and `drjit` versions are typically tightly coupled. We might have introduced a "breaking" change in `drjit` that makes it incompatible with older versions of `mitsuba`. I haven't checked it properly, but I think that's what was causing your error.

**Comment by maxfrei750** [comment]
>I saw this too late.

No worries! After all, you're doing a free service to the community. :+1: 

Thanks for the additional input!
