### ISSUE TITLE
WriteXML fails if the output file doesn't have a directory

### ISSUE THREAD

**Issue by mich-sanna** [mitsuba-renderer/mitsuba3#260]
## Summary

WriteXML fails if the `directory` member is left an empty string

## System configuration

System information:

  OS: Windows-10
  CPU: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
  GPU: Quadro P2000 with Max-Q Design
  Python: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 05:59:00) [MSC v.1929 64 bit (AMD64)]
  NVidia driver: 516.94
  LLVM: 0.0.0

  Dr.Jit: 0.2.2
  Mitsuba: 3.0.2
     Is custom build? False
     Compiled with: MSVC 19.33.31629.0
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb

## Description

if `self.directory` is the empty string (for example if writing to the current working), the function `set_filename` tries to create the directory `''`, and therefore throws an error

## Steps to reproduce

```
import mitsuba

mitsuba.set_variant('cuda_ad_rgb')

from mitsuba import load_dict
from mitsuba.python.xml import dict_to_xml

scene = load_dict({'type': 'scene'})
dict_to_xml(scene, filename='out.xml')
```

Error:

```
Traceback (most recent call last):
  File "C:\Users\Michele.Sanna\AppData\Roaming\JetBrains\PyCharmCE2022.2\scratches\scratch_75.py", line 9, in <module>
    dict_to_xml(scene, filename='out.xml')
  File "C:\Users\Michele.Sanna\.conda\envs\pytorch\lib\site-packages\mitsuba\python\xml.py", line 715, in dict_to_xml
    writer = WriteXML(filename, split_files=split_files)
  File "C:\Users\Michele.Sanna\.conda\envs\pytorch\lib\site-packages\mitsuba\python\xml.py", line 62, in __init__
    self.set_filename(path)
  File "C:\Users\Michele.Sanna\.conda\envs\pytorch\lib\site-packages\mitsuba\python\xml.py", line 148, in set_filename
    os.makedirs(self.directory)
  File "C:\Users\Michele.Sanna\.conda\envs\pytorch\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''
```

**Comment by mich-sanna** [comment]
I took the liberty of fixing this in #259
