### ISSUE TITLE
texture contains pixels that exceed the [0, 1] range after senor moved and scene_params.update()

### ISSUE THREAD

**Issue by GCChen97** [mitsuba-renderer/mitsuba3#315]
## Summary

I made a simple scene and wrote a script to render multi-view images. But after the position of the sensor was modified and the scene parameters `update` in the script, some errors occured.  After the rendering, some shape was missing in the output image and the shading was also abnormally noisy. 

It is confusing that if I do not modified the position of the sensor in the scripts, there will be no warning and the output image will be normal. Why the sensor will affect the texture?

## System configuration

System information:

  OS: Ubuntu 20.04.5 LTS
  CPU: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  Python: 3.9.12 (main, Apr  5 2022, 06:56:58) [GCC 7.5.0]
  CUDA: 11.6.55
  LLVM: 12.0.0

  Dr.Jit: 0.2.2
  Mitsuba: 3.0.2
     Is custom build? True
     Compiled with: Clang 10.0.0
     Variants:
        scalar_rgb
        scalar_rgb_polarized
        llvm_ad_rgb
        llvm_rgb_polarized

## Description

Here is the cmd output:
```
Rendering [===========================================================================================================] (5.18s, ETA: 0ms)     0
Rendering [===========================================================================================================] (4.54s, ETA: 0ms)     1
Rendering [===========================================================================================================] (4.99s, ETA: 0ms)     2

2022-10-10 15:41:22 WARN  main  [BitmapTexture] BitmapTexture: texture named "checkerboard.jpg" contains pixels that exceed the [0, 1] range!
Rendering [===================                                                                                        ] (508ms, ETA: 2.41s)   
2022-10-10 15:41:23 WARN  wrk2  [ImageBlock] Invalid sample value: [0.000883541, 0.00280334, -2.09682e+24, 1]
2022-10-10 15:41:23 WARN  wrk2  [ImageBlock] Invalid sample value: [0.000178584, 8.52342e-05, -6.24777e+23, 1]
Rendering [=========================================================================                                  ] (3.04s, ETA: 1.43s)   
2022-10-10 15:41:25 WARN  wrk4  [ImageBlock] Invalid sample value: [-4.93359e+24, -1.82711e-26, -3.36525e-27, 1]
2022-10-10 15:41:25 WARN  wrk4  [ImageBlock] Invalid sample value: [-3.0893e+24, -2.52329e-27, 0.789702, 1]
2022-10-10 15:41:25 WARN  wrk4  [ImageBlock] Invalid sample value: [-2.02843e+25, -1.81508e-26, -1.38361e-26, 1]
2022-10-10 15:41:25 WARN  wrk4  [ImageBlock] Invalid sample value: [-1.01602e+25, -4.09641e-26, 0.748936, 1]
...
```

Below is the rendering script:

```
import mitsuba as mi

mi.set_variant('scalar_rgb')
scene = mi.load_file("calib.xml")
img = mi.render(scene)
bitmap = mi.Bitmap(img)
channels = dict(bitmap.split())
channels['<root>'].convert(component_format=mi.Struct.Type.UInt8, srgb_gamma=True).write(f'outputs/test_scripts.png')
# so far, the output image is correct.
scene_params = mi.traverse(scene)
Twc = np.array(scene_params["PerspectiveCamera.to_world"].matrix)
tx = Twc[0, 3]

#exit()
# rendering
for i in range(4):
    print(i)
    # translation
    Twc = scene_params["PerspectiveCamera.to_world"]
    scene_params["PerspectiveCamera.to_world"] = Twc.translate([-tx*2/10*i,0,0]) @ scene_params["PerspectiveCamera.to_world"]
    scene_params.update()
    #import pdb;pdb.set_trace()
    img = mi.render(scene)
    bitmap = mi.Bitmap(img) # a shape is missing in the output image and there is much image noise
    channels = dict(bitmap.split())
    channels['<root>'].convert(component_format=mi.Struct.Type.UInt8, srgb_gamma=True).write(f'outputs/{i}.png')
```

## Steps to reproduce

1. download the [scene](https://drive.google.com/file/d/1U0Xb0mRoTEv3hjxEnraOoyOdgEhwjUwX/view?usp=sharing)
2. run `python scripts.py`
3. output images are already included in [scene](https://drive.google.com/file/d/1U0Xb0mRoTEv3hjxEnraOoyOdgEhwjUwX/view?usp=sharing)

**Comment by Speierers** [comment]
Hi @GCChen97 ,

Could you confirm that this issue also arises with using the `llvm_ad_rgb` variant? 

Also did you check that the new `to_world` matrix has the expected values?

**Comment by GCChen97** [comment]
Hi @Speierers ,

I reran the script with `llvm_ad_rgb` but got the following error:
```
Traceback (most recent call last):
  File "/<path>/scripts.py", line 23, in <module>
    scene_params.update()
  File "/<path>/mitsuba3/build/python/mitsuba/python/util.py", line 212, in update
    node.parameters_changed(list(keys))
RuntimeError: slice(): variable contains more than a single entry!
```

I also checked the new `to_world` matrix and it had expected values.

**Comment by GCChen97** [comment]
I did some test:

1. Remove the following shape in the scene file:
```
	<!-- <shape type="obj">
		<string name="filename" value="meshes/backwall.obj"/>
		<boolean name="face_normals" value="true"/>
		<ref id="checkerboard" name="bsdf"/>
	</shape> -->
```
The shape is as simple as follwoing:
```
# Blender 3.3.0
# www.blender.org
o BackWall
v -1.000000 0.000000 -1.000000
v -1.000000 2.000000 -1.000000
v 1.000000 -0.000000 -1.000000
v 1.000000 2.000000 -1.000000
vn -0.0000 -0.0000 -1.0000
vt 1.000000 1.000000
vt 0.000000 1.000000
vt 1.000000 0.000000
vt 0.000000 0.000000
s 0
f 1/1/1 2/2/1 4/4/1 3/3/1
```
At this time, it outputed expected output images but still have the following warning:
```
2022-10-11 16:23:53 WARN  main  [BitmapTexture] BitmapTexture: texture named "checkerboard.jpg" contains pixels that exceed the [0, 1] range!
```

2. Remove the shape and the correspoding material:
```
<bsdf type="diffuse">
			<texture name="reflectance" type="bitmap">
				<string name="filename" value="textures/checkerboard.jpg" />
				<string name="filter_type" value="bilinear" />
			</texture>
		</bsdf>
	</bsdf>
<shape type="obj">
		<string name="filename" value="meshes/backwall.obj"/>
		<boolean name="face_normals" value="true"/>
		<ref id="checkerboard" name="bsdf"/>
	</shape>
```
At this time, outputed images were as expected and there was no warning. But if I use `llvm_ad_rgb`, it would give the same error:
```
Traceback (most recent call last):
  File "/<path>/scripts.py", line 23, in <module>
    scene_params.update()
  File "/<path>/mitsuba3/build/python/mitsuba/python/util.py", line 212, in update
    node.parameters_changed(list(keys))
RuntimeError: slice(): variable contains more than a single entry!
```

**Comment by VijayVikasM** [comment]
Any update regarding this issue?

**Comment by GCChen97** [comment]
No. I have to rewrite and reload the scene xml file for updating the scene, which can also avoid other bugs.

**Comment by njroussel** [comment]
Hi @GCChen97 

I've requested access to the scene - I was unable to replicate this issue with one of my own scenes by simply reusing your script.
