### ISSUE TITLE
Modern Hall scene breaks Mitsuba 3.0 when using AD modes 

### ISSUE THREAD

**Issue by mfischer-ucl** [mitsuba-renderer/mitsuba3#318]
Hi, 

I encountered an error while trying to render the [Modern Hall](https://benedikt-bitterli.me/resources) scene with Mitsuba 3.0. 
Below is a MWE and the error it produces: 

```python
import drjit as dr
import mitsuba as mi

mi.set_variant('cuda_ad_rgb')

scene = mi.load_file("../scenes/staircase2/scene_v3.xml")
img_init = mi.render(scene, seed=0, spp=128)
```

raises the following error: 
```python
Traceback (most recent call last):
  File "/home/X/mitsuba_sampleScenes.py", line 7, in <module>
    img_init = mi.render(scene, seed=0, spp=128)
  File "/home/X/anaconda3/lib/python3.9/site-packages/mitsuba/python/util.py", line 496, in render
    return dr.custom(_RenderOp, scene, sensor, params, integrator,
  File "/home/X/anaconda3/lib/python3.9/site-packages/drjit/router.py", line 5567, in custom
    output = inst.eval(**{ k: _dr.detach(v) for k, v in kwargs.items() })
  File "/home/X/anaconda3/lib/python3.9/site-packages/mitsuba/python/util.py", line 358, in eval
    return self.integrator.render(
drjit.Exception: drjit::detail::collect_indices(): encountered an uninitialized function argument while recording a virtual function call!
```

The same happens when using the `llvm_ad_rgb`. It works with `scalar_rgb`. My output of ` mitsuba.sys_info`: 

```
System information:

  OS: Ubuntu 20.04.4 LTS
  CPU: 12th Gen Intel(R) Core(TM) i9-12900K
  GPU: NVIDIA GeForce RTX 3090
  Python: 3.9.7 (default, Sep 16 2021, 13:09:58) [GCC 7.5.0]
  NVidia driver: 510.85.02
  CUDA: 10.1.243
  LLVM: 12.0.0

  Dr.Jit: 0.2.2
  Mitsuba: 3.0.2
     Is custom build? True
     Compiled with: Clang 9.0.1
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb
```

Does this have to do with the scene file, or is it an issue in Mitsuba? Other scenes (e.g., The Breakfast Room), render fine with all variants.

Best, 
Michael

**Comment by njroussel** [comment]
Hi @mfischer-ucl 

Sorry for the delay, I just tried this and was not able to reproduce it. 
We might have unknowingly fixed this on `master` since the time you originally reported it. Could you try it again please?

**Comment by mfischer-ucl** [comment]
Hi @njroussel 
indeed, it is working now! Thanks for the heads-up :)
