### ISSUE TITLE
CUDA backend does not work on A100 GPU

### ISSUE THREAD

**Issue by benjaminchew** [mitsuba-renderer/mitsuba3#390]
## Summary

I was trying to run an example code from a different repo that used mitsuba and ran into an error: 

`AttributeError: jit_init_thread_state(): the CUDA backend is inactive because no compatible CUDA devices were found on your system.`

To check whether mitsuba was unable to detect CUDA, I ran the 'Hello World!' example from the Getting started section of the documentation with variant set to 'cuda_ad_rgb' and obtained the same error:

```
import mitsuba as mi
mi.set_variant('cuda_ad_rgb')
img = mi.render(mi.load_dict(mi.cornell_box()))
mi.Bitmap(img).write('cbox.exr')
```
I might just be missing something to do with CUDA but the driver and python versions meet the requirements:

**Requirements**

- Python >= 3.8
- (optional) For computation on the GPU: Nvidia driver >= 495.89
- (optional) For vectorized / parallel computation on the CPU: LLVM >= 11.1

## System configuration

System information:

  OS: Ubuntu 20.04.5 LTS
  CPU: Intel(R) Xeon(R) Silver 4214R CPU @ 2.40GHz
  GPU: GRID A100-8C
  Python: 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  NVidia driver: 510.47.03
  CUDA: 11.6.124
  LLVM: 9.0.1

  Dr.Jit: 0.2.2
  Mitsuba: 3.0.2
     Is custom build? False
     Compiled with: GNU 10.2.1
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb

## Description

The errors:

```
- Warning: device does *not* support managed memory, skipping ..
Traceback (most recent call last):
  File "/home/usr/test_dir/sdf/lib/python3.8/site-packages/mitsuba/__init__.py", line 127, in __getattribute__
    _import('mitsuba.mitsuba_' + variant + '_ext'),
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1166, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: jit_init_thread_state(): the CUDA backend is inactive because no compatible CUDA devices were found on your system.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mi_test.py", line 4, in <module>
    mi.set_variant('cuda_ad_rgb')
  File "/home/usr/test_dir/sdf/lib/python3.8/site-packages/mitsuba/__init__.py", line 340, in set_variant
    _import('mitsuba.ad.integrators')
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/usr/test_dir/sdf/lib/python3.8/site-packages/mitsuba/python/ad/__init__.py", line 1, in <module>
    from .integrators import *
  File "/home/usr/test_dir/sdf/lib/python3.8/site-packages/mitsuba/python/ad/integrators/__init__.py", line 25, in <module>
    importlib.import_module('mitsuba.ad.integrators.' + name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/usr/test_dir/sdf/lib/python3.8/site-packages/mitsuba/python/ad/integrators/direct_reparam.py", line 6, in <module>
    from .common import ADIntegrator, mis_weight
  File "/home/usr/test_dir/sdf/lib/python3.8/site-packages/mitsuba/python/ad/integrators/common.py", line 8, in <module>
    class ADIntegrator(mi.CppADIntegrator):
  File "/home/usr/test_dir/sdf/lib/python3.8/site-packages/mitsuba/__init__.py", line 276, in __getattribute__
    result = module.__getattribute__(key)
  File "/home/usr/test_dir/sdf/lib/python3.8/site-packages/mitsuba/__init__.py", line 138, in __getattribute__
    raise AttributeError(e)
AttributeError: jit_init_thread_state(): the CUDA backend is inactive because no compatible CUDA devices were found on your system.
```

## Steps to reproduce

1. Ran the 'Hello World' example with variant set to cuda_ad_rgb

**Comment by wjakob** [comment]
Hi @benjaminchew,

the A100 is a machine learning-focused GPU (for example, it has zero ray tracing cores). I think it is quite likely that OptiX is simply not supported on it, and that's why Mitsuba is complaining. Could you try running some of the OptiX SDK examples to see if those work?

Thanks,
Wenzel

**Comment by wjakob** [comment]
I will close this for now, feel free to message here if you have further observations and we can reopen the issue.

**Comment by joeylitalien** [comment]
For what it's worth, I have no problem running Mitsuba on a A100. I'm using drivers 535.54.03 and CUDA 11.7 and it works like a charm.
