### ISSUE TITLE
Compiling with Mac M1

### ISSUE THREAD

**Issue by minhpvo** [mitsuba-renderer/mitsuba3#569]
## Summary

Incompatibility between Arm64 and x86_64 issue when compiling in Mac M1 chip

## System configuration

System configuration:
OSX Ventura 13.1
Python 3.9
LLVM version: Unknown
Dr.Jit version: 0.4.1
Mitsuba version: 3.1.1
Compiled with: llvm
Variants compiled: llvm_ad_rgb

## Steps to reproduce

1. compile using pip

```
pip install mitsuba
Collecting mitsuba
  Using cached mitsuba-3.2.1-cp39-cp39-macosx_10_14_x86_64.whl (26.7 MB)
Collecting drjit==0.4.1
  Using cached drjit-0.4.1-cp39-cp39-macosx_10_14_x86_64.whl (3.0 MB)
Installing collected packages: drjit, mitsuba
Successfully installed drjit-0.4.1 mitsuba-3.2.1
```
Error at run time:
```
python
import mitsuba as mi
zsh: illegal hardware instruction  python
```
2. Compile from source
```
brew install llvm
xcode-select --install
git clone --recursive https://github.com/mitsuba-renderer/mitsuba3
mkdir build
cd build
cmake -GNinja ..
ninja
```
Error message:
```
FAILED: python/drjit/__init__.pyi /Users/minhvo/Research/thirdparty/mitsuba3/build/python/drjit/__init__.pyi 
cd /Users/minhvo/Research/thirdparty/mitsuba3/build/src/python && /opt/homebrew/Cellar/cmake/3.25.2/bin/cmake -E env PYTHONPATH=/Users/minhvo/Research/thirdparty/mitsuba3/build/python: /Users/minhvo/opt/anaconda3/bin/python3.9 -Xutf8 /Users/minhvo/Research/thirdparty/mitsuba3/ext/drjit/resources/generate_stub_files.py /Users/minhvo/Research/thirdparty/mitsuba3/build/python/drjit
Traceback (most recent call last):
  File "/Users/minhvo/Research/thirdparty/mitsuba3/ext/drjit/resources/generate_stub_files.py", line 347, in <module>
    import drjit as dr
  File "/Users/minhvo/Research/thirdparty/mitsuba3/build/python/drjit/__init__.py", line 37, in <module>
    import drjit.drjit_ext as drjit_ext  # noqa
ImportError: dlopen(/Users/minhvo/Research/thirdparty/mitsuba3/build/python/drjit/drjit_ext.cpython-39-darwin.so, 0x0002): tried: '/Users/minhvo/Research/thirdparty/mitsuba3/build/python/drjit/drjit_ext.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/minhvo/Research/thirdparty/mitsuba3/build/python/drjit/drjit_ext.cpython-39-darwin.so' (no such file), '/Users/minhvo/Research/thirdparty/mitsuba3/build/python/drjit/drjit_ext.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
```

**Comment by njroussel** [comment]
Hi @minhpvo 

In the `pip install` logs you can see that it is downloading the x86 version, this lets me to believe that your shell and python are both x86 binaries.  You should be using the ARM versions of these.

**Comment by minhpvo** [comment]
Thanks. I pull the correct anaconda version to run python and it works!
